Return-Path: <lvs-devel-owner@vger.kernel.org>
X-Original-To: lists+lvs-devel@lfdr.de
Delivered-To: lists+lvs-devel@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id EFCD24BCE17
	for <lists+lvs-devel@lfdr.de>; Sun, 20 Feb 2022 12:13:52 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229667AbiBTLMt (ORCPT <rfc822;lists+lvs-devel@lfdr.de>);
        Sun, 20 Feb 2022 06:12:49 -0500
Received: from mxb-00190b01.gslb.pphosted.com ([23.128.96.19]:45588 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229480AbiBTLMs (ORCPT
        <rfc822;lvs-devel@vger.kernel.org>); Sun, 20 Feb 2022 06:12:48 -0500
X-Greylist: delayed 586 seconds by postgrey-1.37 at lindbergh.monkeyblade.net; Sun, 20 Feb 2022 03:12:27 PST
Received: from mg.ssi.bg (mg.ssi.bg [193.238.174.37])
        by lindbergh.monkeyblade.net (Postfix) with ESMTP id 019143CA7E
        for <lvs-devel@vger.kernel.org>; Sun, 20 Feb 2022 03:12:26 -0800 (PST)
Received: from mg.ssi.bg (localhost [127.0.0.1])
        by mg.ssi.bg (Proxmox) with ESMTP id 7C97428D17;
        Sun, 20 Feb 2022 13:02:38 +0200 (EET)
Received: from ink.ssi.bg (unknown [193.238.174.40])
        by mg.ssi.bg (Proxmox) with ESMTP id 80AEE28ABE;
        Sun, 20 Feb 2022 13:02:37 +0200 (EET)
Received: from ja.ssi.bg (unknown [178.16.129.10])
        by ink.ssi.bg (Postfix) with ESMTPS id 65D423C0332;
        Sun, 20 Feb 2022 13:02:34 +0200 (EET)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
        by ja.ssi.bg (8.16.1/8.16.1) with ESMTP id 21KB2UXn023295;
        Sun, 20 Feb 2022 13:02:32 +0200
Date:   Sun, 20 Feb 2022 13:02:30 +0200 (EET)
From:   Julian Anastasov <ja@ssi.bg>
To:     "Sergey V. Lobanov" <sergey@lobanov.in>
cc:     Jesper Dangaard Brouer <brouer@redhat.com>,
        Simon Horman <horms@verge.net.au>, lvs-devel@vger.kernel.org
Subject: Re: [PATCH] ipvsadm: allow to redefine AR (libipvs)
In-Reply-To: <20220204215215.94422-1-sergey@lobanov.in>
Message-ID: <5bd787cd-aba-88cb-ad8e-a197af6bf19b@ssi.bg>
References: <20220204215215.94422-1-sergey@lobanov.in>
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
X-Spam-Status: No, score=-1.9 required=5.0 tests=BAYES_00,SPF_HELO_NONE,
        T_SCC_BODY_TEXT_LINE,T_SPF_PERMERROR autolearn=ham autolearn_force=no
        version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <lvs-devel.vger.kernel.org>
X-Mailing-List: lvs-devel@vger.kernel.org


	Hello,

On Sat, 5 Feb 2022, Sergey V. Lobanov wrote:

> libipvs Makefile uses `ar` to build archive. On cross-compile
> cross-platfrom build it fails due system ar might be incompatible
> with the objects generated by $(CC). It happens if build ipvsadm
> on macos using GCC Toolchain (Linux target)
> 
> This patch allows to redefine `ar` using AR var in libipvs Makefile
> 
> Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>

	Looks good to me, thanks!

Acked-by: Julian Anastasov <ja@ssi.bg>

> ---
>  libipvs/Makefile | 3 ++-
>  1 file changed, 2 insertions(+), 1 deletion(-)
> 
> diff --git a/libipvs/Makefile b/libipvs/Makefile
> index f845c8b..7e02d4d 100644
> --- a/libipvs/Makefile
> +++ b/libipvs/Makefile
> @@ -1,5 +1,6 @@
>  # Makefile for libipvs
>  
> +AR		= ar
>  CC		= gcc
>  CFLAGS		= -Wall -Wunused -Wstrict-prototypes -g -fPIC
>  ifneq (0,$(HAVE_NL))
> @@ -30,7 +31,7 @@ SHARED_LIB	= libipvs.so
>  all:		$(STATIC_LIB) $(SHARED_LIB)
>  
>  $(STATIC_LIB):	libipvs.o ip_vs_nl_policy.o
> -		ar rv $@ $^
> +		$(AR) rv $@ $^
>  
>  $(SHARED_LIB):	libipvs.o ip_vs_nl_policy.o
>  		$(CC) -shared -Wl,-soname,$@ -o $@ $^
> -- 
> 2.32.0 (Apple Git-132)

Regards

--
Julian Anastasov <ja@ssi.bg>

