Return-Path: <lvs-devel-owner@vger.kernel.org>
X-Original-To: lists+lvs-devel@lfdr.de
Delivered-To: lists+lvs-devel@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id B252838E8C5
	for <lists+lvs-devel@lfdr.de>; Mon, 24 May 2021 16:33:28 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S232972AbhEXOez (ORCPT <rfc822;lists+lvs-devel@lfdr.de>);
        Mon, 24 May 2021 10:34:55 -0400
Received: from mail-io1-f72.google.com ([209.85.166.72]:33376 "EHLO
        mail-io1-f72.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S232920AbhEXOex (ORCPT
        <rfc822;lvs-devel@vger.kernel.org>); Mon, 24 May 2021 10:34:53 -0400
Received: by mail-io1-f72.google.com with SMTP id d14-20020a056602328eb029043afd25c9efso25988574ioz.0
        for <lvs-devel@vger.kernel.org>; Mon, 24 May 2021 07:33:25 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
        bh=mzMzgGXGzf6LXhHO5i6yc8Y+EDUJAYcIfexi+vE47CU=;
        b=mC11PN+DfuZwoIziNYiwzDdZE7+v+0tdlN93AFolZxXcxNpeI+jgDe8B2ulDEz4j+n
         Zp47N67LOfcQ4PXinyO6USYpxM/fZNcOEpQF+Q0ZZJyqBczBzuMyWd/VH5DT5AZyNWNK
         8cvFginl04JdaEfllc7C9elxVYxby/TKuFPsa5wpUdSrnqgLRik1xX+VY95aevob6mFP
         ct9dXrbGHrT2XW9xK4sRmWGbAT987tgM8N500VKGn1riJDlgvTsWK+JbnqhHM0PNayCh
         FJTVKm1h8BSSteIm+wFbQLWJR7nddGC2c8PlN43iwX0oIWvKuffJpiThVYWcMs5m0dAK
         mjlA==
X-Gm-Message-State: AOAM531PyrxcwCEcx4NEV3H9hFAqhl99DW8VmEy1unz8VafWUKlI915i
        WSKfEqcvwLVZtjydM02P+IVHxzPJGL3i3/RO7hIBFw69fV5V
X-Google-Smtp-Source: ABdhPJwcLmlxYie5V2pawuvy04hy/JhXmHluK7avvoMDLz8HPqTWiVk6pB4ev4axH1fIOY+cFZD0NJBTXl7Xe+dCdaOexF+vy7zQ
MIME-Version: 1.0
X-Received: by 2002:a05:6e02:b47:: with SMTP id f7mr18755134ilu.261.1621866805007;
 Mon, 24 May 2021 07:33:25 -0700 (PDT)
Date:   Mon, 24 May 2021 07:33:24 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000c91e6f05c3144acc@google.com>
Subject: [syzbot] memory leak in ip_vs_add_service
From:   syzbot <syzbot+e562383183e4b1766930@syzkaller.appspotmail.com>
To:     coreteam@netfilter.org, davem@davemloft.net, fw@strlen.de,
        horms@verge.net.au, ja@ssi.bg, kadlec@netfilter.org,
        kuba@kernel.org, linux-kernel@vger.kernel.org,
        lvs-devel@vger.kernel.org, netdev@vger.kernel.org,
        netfilter-devel@vger.kernel.org, pablo@netfilter.org,
        syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
Precedence: bulk
List-ID: <lvs-devel.vger.kernel.org>
X-Mailing-List: lvs-devel@vger.kernel.org

Hello,

syzbot found the following issue on:

HEAD commit:    c3d0e3fd Merge tag 'fs.idmapped.mount_setattr.v5.13-rc3' o..
git tree:       upstream
console output: https://syzkaller.appspot.com/x/log.txt?x=148d0bd7d00000
kernel config:  https://syzkaller.appspot.com/x/.config?x=ae7b129a135ab06b
dashboard link: https://syzkaller.appspot.com/bug?extid=e562383183e4b1766930
syz repro:      https://syzkaller.appspot.com/x/repro.syz?x=15585a4bd00000
C reproducer:   https://syzkaller.appspot.com/x/repro.c?x=13900753d00000

IMPORTANT: if you fix the issue, please add the following tag to the commit:
Reported-by: syzbot+e562383183e4b1766930@syzkaller.appspotmail.com

BUG: memory leak
unreferenced object 0xffff888115227800 (size 512):
  comm "syz-executor263", pid 8658, jiffies 4294951882 (age 12.560s)
  hex dump (first 32 bytes):
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  backtrace:
    [<ffffffff83977188>] kmalloc include/linux/slab.h:556 [inline]
    [<ffffffff83977188>] kzalloc include/linux/slab.h:686 [inline]
    [<ffffffff83977188>] ip_vs_add_service+0x598/0x7c0 net/netfilter/ipvs/ip_vs_ctl.c:1343
    [<ffffffff8397d770>] do_ip_vs_set_ctl+0x810/0xa40 net/netfilter/ipvs/ip_vs_ctl.c:2570
    [<ffffffff838449a8>] nf_setsockopt+0x68/0xa0 net/netfilter/nf_sockopt.c:101
    [<ffffffff839ae4e9>] ip_setsockopt+0x259/0x1ff0 net/ipv4/ip_sockglue.c:1435
    [<ffffffff839fa03c>] raw_setsockopt+0x18c/0x1b0 net/ipv4/raw.c:857
    [<ffffffff83691f20>] __sys_setsockopt+0x1b0/0x360 net/socket.c:2117
    [<ffffffff836920f2>] __do_sys_setsockopt net/socket.c:2128 [inline]
    [<ffffffff836920f2>] __se_sys_setsockopt net/socket.c:2125 [inline]
    [<ffffffff836920f2>] __x64_sys_setsockopt+0x22/0x30 net/socket.c:2125
    [<ffffffff84350efa>] do_syscall_64+0x3a/0xb0 arch/x86/entry/common.c:47
    [<ffffffff84400068>] entry_SYSCALL_64_after_hwframe+0x44/0xae



---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

syzbot will keep track of this issue. See:
https://goo.gl/tpsmEJ#status for how to communicate with syzbot.
syzbot can test patches for this issue, for details see:
https://goo.gl/tpsmEJ#testing-patches
